name: 'deploy-to-google-cloud-functions'
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/deploy-to-google-cloud-functions.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Compile Typescript
        run: yarn build

      - id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          workload_identity_provider: ${{ secrets.GOOGLE_CLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT }}

      - id: 'deploy-infura-mainnet'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'infura-mainnet'
          runtime: 'nodejs16'
          entry_point: './dist/infuraMainnet.js'
          env_vars: 'INFURA_MAINNET_URL=${{ secrets.INFURA_MAINNET_URL }},SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }},SLACK_APPS_ALERTING_CHANNEL=${{ secrets.SLACK_APPS_ALERTING_CHANNEL }},TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}'

      - id: 'deploy-infura-goerli'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'infura-goerli'
          runtime: 'nodejs16'
          entry_point: './dist/infuraGoerli.js'
          env_vars: 'INFURA_GOERLI_URL=${{ secrets.INFURA_GOERLI_URL }},SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }},SLACK_APPS_ALERTING_CHANNEL=${{ secrets.SLACK_APPS_ALERTING_CHANNEL }},TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}'

      - id: 'deploy-subgraph-mainnet'
        uses: 'google-github-actions/deploy-cloud-functions@v0'
        with:
          name: 'subgraph-mainnet'
          runtime: 'nodejs16'
          entry_point: './dist/subgraphMainnet.js'
          env_vars: 'SUBGRAPH_MAINNET_URL=${{ secrets.SUBGRAPH_MAINNET_URL }},SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }},SLACK_APPS_ALERTING_CHANNEL=${{ secrets.SLACK_APPS_ALERTING_CHANNEL }},TELEGRAM_BOT_TOKEN=${{ secrets.TELEGRAM_BOT_TOKEN }},TELEGRAM_CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}'
